# Your name and what you do
name: Suveer Garg
bio: Robotics Software Engineer, University of Pennsylvania

description: Portfolio Page

# Profile picture
picture: assets/images/profile.png

# your url: http://USERNAME.github.io
url: https://suveergarg.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
linkedin: suveergarg
github: suveergarg
email: gargsuveer@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large
# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python, C++, C
    - Sklearn, Numpy, tensorflow, pandas, Matplotlib, PyTorch, MLFlow, Sagemaker
    - Altium Designer, Atmel Studio, Visual Studio, Docker, k8s, Django, PostgreSQL    
    - Linux, ROS, AWS
    - Quick Prototyping Boards (Arduino, Raspberrry Pi), SAMD21(ARM 32 bit)	

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Oishii - World's first and largest indoor strawberry vertical farm:
        num: 1
        name: Robotic harvesting system for Strawberries
        description: Maintained 60 robots in production with minimal downtime. Improved pick accuracy by 25% and reduced collateral damage to under 5% by using 3D vision solutions in production. Created an ML training pipeline to improve mAP values of instance segmentation and keypoint detection R-CNN models. Developed system to collect pick-metrics (successful, missed & dropped), vision-system metrics (latency & rejections) and farm-metrics (coverage & berry counts), helping multiple teams make data-driven decisions.  
        video: assests/videos/OishiiHarvesting.webm
        
    HIO-SDF - Hierarchical Incremental Online Signed Distance Field:
        num: 2
        name: HIO-SDF - Hierarchical Incremental Online Signed Distance Field
        description: Developed a novel method for constructing a differentiable global SDF for real-time planning in unknown environments. HIO-SDF employs a coarse voxel grid that captures the observed parts of the environment together with high-resolution local information to train a neural network that represents the environment as a Signed Distance Field (SDF). More details in the project page linked below. 
        link: https://samsunglabs.github.io/HIO-SDF-project-page/
        link1: https://arxiv.org/pdf/2310.09463.pdf
        link2: https://github.com/SamsungLabs/HIO-SDF
        video: assets/videos/hio_sdf.mp4
    
    RAMP - Hierarchical Reactive Motion Planning for Manipulation Tasks Using Implicit Signed Distance Functions:
        num: 3 
        name: RAMP - Hierarchical Reactive Motion Planning for Manipulation Tasks Using Implicit Signed Distance Functions
        description: Reactive Action and Motion Planner (RAMP), a hierarchical approach where a novel variant of a Model Predictive Path Integral (MPPI) controller is used to generate trajectories which are then followed asynchronously by a local vector field controller. RAMP can rapidly find paths in the robot's configuration space, satisfy task and robot-specific constraints, and provide safety by reacting to static or dynamically moving obstacles. More details in the project page linked below. 
        link: https://samsunglabs.github.io/RAMP-project-page/
        link1: https://arxiv.org/pdf/2305.10534.pdf
        link2: https://github.com/SamsungLabs/RAMP
        video: assets/videos/ramp.mp4

    Path planning, minimum jerk trajectory generation & PID controller for quadrotors:
        num: 4 
        name: Path planning, minimum jerk trajectory generation & PID control for quadrotor
        description: Path planning using A*, smoothing using piecewise minimum trajectory generation and PID control for quadrotor navigation in an indoor obstacle course. Additionally implemented a VIO pipeline for state estimation. 
        video: assets/videos/MEAM620.mp4   

    Deep Learning for Computer Vision:
        num: 5	
        name: Deep Learning for Computer Vision
        description: Implemented YOLO, SOLO, VAE, DCGAN, Cyclic GAN and Faster Mask-RNN. Course Project - Experimented with a state of the art method that uses Ordinal depth supervision for 3D human pose estimation from single 2D images. This method tackles the lack of availability/variability of 3D ground truth pose data for natural images. Please visit the github links below for more infomation on these projects.
        link: https://github.com/suveergarg/SOLO
        link1: https://github.com/suveergarg/YOLO
        link2: https://github.com/suveergarg/Faster-RCNN
        link3: https://github.com/suveergarg/VAE-GAN
        link4: https://github.com/suveergarg/PoseReconstruction
        video: assets/videos/680.mp4
           
    Pick and Place using the 5-DOF Lynx arm in Gazebo: 
        num: 6
        name: Pick and Place using the Lynx arm in Gazebo
        description: Used Forward and Inverse velocity and position kinematics to stack blocks in a simulation environment. Won a stacking competition as part of the class final project.
        video: assets/videos/MEAM520.mp4   


    RRT*, Particle Filter Based SLAM and Autonomous Quadrotor Landing on Moving Platform: 
        num: 7  
        name: RRT*, Particle Filter Based SLAM and Autonomous Quadrotor Landing on Moving Platform
        description: Implemented Unscented Kalman Filter, particle filter SLAM with LIDAR data, RRT* algorithm. Simulated autonomous quad-rotor landing on a moving platform using Aruco markers and minimum jerk quad-rotor trajectory using Gazebo and ROS.
        link: https://github.com/suveergarg/uav_landing   
        video: assets/videos/Slam.mp4

    Image Stitching and Optical Tracking:
        num: 8
        name: Image Stitching and Optical Tracking
        description: Created python modules for edge and corner detection, adaptive non-maximal suppression, homography estimation, feature matching using knn, outlier detection with RANSAC and poisson blending to produce smooth stitched images and videos. Additionally, implemented Lucas Kanade optical flow tracking algorithm to track moving objects in a video.
        link: https://github.com/suveergarg/cis581-3A 
        video: assets/videos/CIS581.mp4


    Intelligent Travel Friendly Medicine Dispenser:
        num: 9 
        name: Intelligent Travel Friendly Medicine Dispenser
        description: Designed an IoT medicine dispenser with automatic alerts for refilling, dose collection and location tracking. The end-to-end design process involved part selection, PCB layout, CAD design, power architecture design, Over The Air Firmware Update and custom bootloader design, wireless communications and firmware design. 
        link: https://github.com/briankwn/SmartDose  
        video: assets/videos/ESE516.mp4

    Multi-Robot Sorting System:
        num: 10
        name: Multi-Robot Parcel Sorting System
        description: Designed a ROS based simulation for multi-robot parcel sorting system. Developed software for map creation, planning, movement, diagnostics and evaluation of 120 robots. Introduced improvements which quadrupled the throughput of the system. 
        video: assets/videos/addverb.mp4
    
    Ecofrost Technologies Pvt. Ltd.:
        num: 12
        name: Ecofrost Technologies, Internship, Pune 2017-2018
        description: Built capacitive sensing based embedded prototype for charge level measurement in Thermal batteries using level sensing of phase change material for energy management and temperature control in solar powered cold-storage units. Rectified errors after analysing data collected from prototype. At the end of the internship, I presented my results and offered a new approach to attain the objective of energy management for the system using the same sensor based on the learnings from the test experiments.
        video: assets/videos/eco.mp4
      
    Smart Dustbin Project:
        num: 13
        name: Smart Dustbin Project, WeConvert, New Delhi 2017-2018
        description: The Smart dustbin was a Raspberry-Pi based system to classify waste objects and reward the user with credits based on what is dropped in the bin. It makes use of Image Processing algorithms to classify objects and sort trash. My work involved developing the detection algorithms, human machine interface and firmware for the embedded systems.The system was tested at various colleges, malls, and public places. The initiative was covered by media agencies such as DuBeat, Your Story and ZeeTv.
        video: assets/videos/weconvert.mp4 	
 
# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
