# Your name and what you do
name: Suveer Garg
bio: Systems Engineer

description: Suveer's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://suveergarg.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
linkedin: https://www.linkedin.com/in/suveer-garg-6974a0a4/
github: https://github.com/suveergarg
email: gargsuveer@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python,C++
    - Altium Designer, Atmel Studio, Visual Studio    
    - Linux, ROS, open-frameworks
    - Image processing (OpenCV)
    - Data Science (Keras, Scipy)
    - Quick Prototyping Boards (Arduino, Raspberrry pi)	

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Unmanned Ground Vehicles Team:
        name: Unmanned Ground Vehicle, DTU 2017-2018
        description: Founded and Lead a team of 6 students in building a automated ground vehicle under the Robot Operating System Framework, to participate in the IGVC competition held in Oakland, U.S.A. Responsible for team operations, raising funds and embedded systems development. My work involved interfacing the IMU and motor Drivers through the microcontroller to communicate with the main system as a ROS node.
        video: assets/videos/ugv.webm	      

#    Tangible User Interface for Smart Mirror:
#        name: Tangible User Interface for Smart Mirror
#        description: This project under Prof.Aman Parnami at IIITD, Weave Lab, explored the application of a tangible user interface for mirrors of the future. Various interaction use cases were ideated that explored areas such as sharing stories, post-surgery rehabilitation and construction toolkits. My work involved writing the image processing, UI and embedded systems code under open-frameworks. It also involved writing use-cases and ideating with the team.
#	 video: abc.mp4  
     

    
    Ecofrost Technologies Pvt. Ltd.:
        name: Ecofrost Technologies, Internship, Pune 2017-2018
        description: During my internship, I was tasked with the conception of a charge measurement device for thermal storage batteries which cannot be measured using conventional methods. After exploring different methods, I settled for capacitive sensing. I used TI's capacitive to digital converters and Atmels mirocontrollers to develop a prototype of the same. My work involved designing the PCBs which required careful deliberation because we were dealing primarily with capacitance. It also involved developing firmware, design of experiments for testing, debugging, collection and analysis of data from the sensor. At the end of the internship, I was able to present my results and correct for various unanticipated errors. I also offered a new approach to attain the objective of energy management for the system using the sensor which had not been considered before.
        video: assets/videos/eco.mp4
      
 
    Smart Dustbin Project:
        name: Smart Dustbin Project, WeConvert, New Delhi 2017-2018
        description: The Smart dustbin was a raspberry pi based system to classify waste objects and reward the user with credits based on what is dropped in the bin. It makes use of Image Processing Alogorithms to classify objects and the hardware interfaced through the raspberry pi drops it in the right bin and communicates with the user through the Human machine interface. My work involved delveloping the detection algorithms, HMI and embedded systems development.The system was tested at various colleges, malls, and public places. I was covered by media agencies such as DuBeat, Your Story and ZeeTv.
        video: assets/videos/weconvert.webm 	
 
    Three Degree Of Freedom Robotic Arm:
        name: Three Degree of Freedom Robotic Arm
        description: This was built in a team of three for my minor project in university during my undergraduate degree under the ROS framework. My work involved making the Robot description files(URDFs) and setting up MoveIt and sending goal positions to the micro-controller.
        video: assets/videos/arm.webm 

    Object Follower:
        name: Object Follower
        description: Raspberry pi based system that tracks an object in the HSV color space using blob detection and positions the motors such that the object lies in the centre of the camera frame. 
        video: assets/videos/Track.webm
      
    Beat Detection:
        name: Beat Detection
        description: This project involved performing FFT on Audio signal for beat detection and interfacing servo motors to react to the sensed beats.
        video: assets/videos/beat.mp4
       
    Line Follower Robot:
        name: Line Follower Robot
        description: This is a simple Line Follower built using light sensitive resistors and automatic calibration for different lighting scenarios.
        video: assets/videos/Line_Follower.webm
        
    Artist:
        name: Artist
        description: This is a simple project made using junk material to draw simple shapes through the motor assembly controlled by the Atmel micro-controller using L293D motor driver.
        video: assets/videos/Artist.mp4

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
