# Your name and what you do
name: Suveer Garg
bio: Robotics Software Engineer, University of Pennsylvania

description: Portfolio Page

# Profile picture
picture: assets/images/profile.png

# your url: http://USERNAME.github.io
url: https://suveergarg.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
linkedin: suveergarg
github: suveergarg
email: gsuveer@seas.upenn.edu
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large
# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python,C++, C
    - Sklearn, Numpy, tensorflow, pandas, Matplotlib, pytorch
    - Altium Designer, Atmel Studio, Visual Studio, Docker    
    - Linux, ROS, Open-Frameworks
    - Quick Prototyping Boards (Arduino, Raspberrry Pi), SAMD21(ARM 32 bit)	

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Path planning, minimum jerk trajectory generation & PID controller for quadrotors: 
        name: Path planning, minimum jerk trajectory generation & PID control for quadrotor
        description: Path planning using A*, smoothing using piecewise minimum trajectory generation and PID control for quadrotor navigation in an indoor obstacle course. Additionally implemented a VIO pipeline for state estimation. 
        video: assets/videos/MEAM620.mp4   

    Deep Learning for Computer Vision:
        name: Deep Learning for Computer Vision
        description: Implemented YOLO, SOLO, VAE, DCGAN, Cyclic GAN and Faster Mask-RNN. Course Project - Experimented with a state of the art method that uses Ordinal depth supervision for 3D human pose estimation from single 2D images. This method tackles the lack of availability/variability of 3D ground truth pose data for natural images. Please visit the github links below for more infomation on these projects.
        link: https://github.com/suveergarg/SOLO
        link1: https://github.com/suveergarg/YOLO
        link2: https://github.com/suveergarg/Faster-RCNN
        link3: https://github.com/suveergarg/VAE-GAN
        link4: https://github.com/suveergarg/PoseReconstruction
        video: assets/videos/680.mp4
           
    Pick and Place using the 5-DOF Lynx arm in Gazebo: 
        name: Pick and Place using the Lynx arm in Gazebo
        description: Used Forward and Inverse velocity and position kinematics to stack blocks in a simulation environment. Won a stacking competition as part of the class final project.
        video: assets/videos/MEAM520.mp4   


    RRT*, Particle Filter Based SLAM and Autonomous Quadrotor Landing on Moving Platform: 
        name: RRT*, Particle Filter Based SLAM and Autonomous Quadrotor Landing on Moving Platform
        description: Implemented Unscented Kalman Filter, particle filter SLAM with LIDAR data, RRT* algorithm. Simulated autonomous quad-rotor landing on a moving platform using Aruco markers and minimum jerk quad-rotor trajectory using Gazebo and ROS.
        link: https://github.com/suveergarg/uav_landing   
        video: assets/videos/Slam.mp4


    Image Stitching and Optical Tracking:
        name: Image Stitching and Optical Tracking
        description: Created python modules for edge and corner detection, adaptive non-maximal suppression, homography estimation, feature matching using knn, outlier detection with RANSAC and poisson blending to produce smooth stitched images and videos. Additionally, implemented Lucas Kanade optical flow tracking algorithm to track moving objects in a video.
        link: https://github.com/suveergarg/cis581-3A 
        video: assets/videos/CIS581.mp4


    Intelligent Travel Friendly Medicine Dispenser: 
        name: Intelligent Travel Friendly Medicine Dispenser
        description: Designed an IoT medicine dispenser with automatic alerts for refilling, dose collection and location tracking. The end-to-end design process involved part selection, PCB layout, CAD design, power architecture design, Over The Air Firmware Update and custom bootloader design, wireless communications and firmware design. 
        link: https://github.com/briankwn/SmartDose  
        video: assets/videos/ESE516.mp4


    Multi-Robot Sorting System:
        name: Multi-Robot Parcel Sorting System
        description: Designed a ROS based simulation for multi-robot parcel sorting system. Developed software for map creation, planning, movement, diagnostics and evaluation of 120 robots. Introduced improvements which quadrupled the throughput of the system. 
        video: assets/videos/addverb.mp4
    

    Unmanned Ground Vehicles Team:
        name: Unmanned Ground Vehicle, DTU 2017-2018
        description: Founded and led a team of 6 students in building a automated ground vehicle under the Robot Operating System to participate in the IGVC competition held in Oakland, U.S.A. Responsible for team operations, raising funds and embedded systems development. My work involved interfacing the IMU and motor drivers through the microcontroller to communicate with the main system as a ROS node.
        video: assets/videos/ugv.mp4	      

#    Tangible User Interface for Smart Mirror:
#        name: Tangible User Interface for Smart Mirror
#        description: This project under Prof.Aman Parnami at IIITD, Weave Lab, explored the application of a tangible user interface for mirrors of the future. Various interaction use cases were ideated that explored areas such as sharing stories, post-surgery rehabilitation and construction toolkits. My work involved writing the image processing, UI and embedded systems code under open-frameworks. It also involved writing use-cases and ideating with the team.
#	 video: abc.mp4  
     

    Ecofrost Technologies Pvt. Ltd.:
        name: Ecofrost Technologies, Internship, Pune 2017-2018
        description: Built capacitive sensing based embedded prototype for charge level measurement in Thermal batteries using level sensing of phase change material for energy management and temperature control in solar powered cold-storage units. Rectified errors after analysing data collected from prototype. At the end of the internship, I presented my results and offered a new approach to attain the objective of energy management for the system using the same sensor based on the learnings from the test experiments.
        video: assets/videos/eco.mp4
      
 
    Smart Dustbin Project:
        name: Smart Dustbin Project, WeConvert, New Delhi 2017-2018
        description: The Smart dustbin was a Raspberry-Pi based system to classify waste objects and reward the user with credits based on what is dropped in the bin. It makes use of Image Processing algorithms to classify objects and sort trash. My work involved developing the detection algorithms, human machine interface and firmware for the embedded systems.The system was tested at various colleges, malls, and public places. The initiative was covered by media agencies such as DuBeat, Your Story and ZeeTv.
        video: assets/videos/weconvert.mp4 	
 
    Three Degree Of Freedom Robotic Arm:
        name: Three Degree of Freedom Robotic Arm
        description: This was built in a team of three for my minor project in university during my undergraduate career. My work involved making the robot description files(URDFs), setting up MoveIt and sending goal positions to the micro-controller using the ROS framework.
        video: assets/videos/arm.mp4 

    Object Follower:
        name: Object Follower
        description: Raspberry Pi based system that tracks an object in the HSV color space using blob detection and controls the motors such that the object lies in the center of the camera frame.
        video: assets/videos/Track.mp4
      
    Beat Detection:
        name: Beat Detection
        description: This project involved performing FFT on audio signals for beat detection and controlling servo motors to react to the sensed beats.
        video: assets/videos/beat.mp4
       
    Line Follower Robot:
        name: Line Follower Robot
        description: This is a simple line follower built using light sensitive resistors and automatic calibration for different lighting scenarios.
        video: assets/videos/Line_Follower.mp4
        
    Artist:
        name: Artist
        description: This is a simple project made using junk material to draw simple shapes using the motor assembly controlled by an 8 bit atmel micro-controller through L293D motor driver.
        video: assets/videos/Artist.mp4

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
