# Your name and what you do
name: Suveer Garg
bio: Graduate Student, University of Pennsylvania

description: Portfolio Page

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://suveergarg.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
linkedin: https://www.linkedin.com/in/suveer-garg-6974a0a4/
github: https://github.com/suveergarg
email: gsuveer@seas.upenn.edu
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python,C++
    - Altium Designer, Atmel Studio, Visual Studio    
    - Linux, ROS, Open-Frameworks
    - Image Processing (OpenCV)
    - Data Science (Keras, Scipy)
    - Quick Prototyping Boards (Arduino, Raspberrry Pi)	

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Intelligent Travel Friendly Medicine Dispenser: 
        name: Intelligent Travel Friendly Medicine Dispenser
        description: Designed from scratch, an IoT travel friendly medicine dispenser with automatic alerts for refilling, dose collection and location tracking. The end-to-end design process involves part selection, PCB layout, CAD design, power architecture design, Over The Air Firmware Update and bootloader design, wireless communications, component integration and writing firmware.  
        video: assets/videos/ESE516.mov

    Image Stitching and Optical Tracking:
        name: Image Stitching and Optical Tracking
        description: As part of a graduate Computer Vision course, created from scratch modules to find features in images, estimate homography, perform RANSAC, match features across images and blend frames to produce smooth stitched images and videos. Additionally, implemented LCT optical flow tracking algorithm to track objects in a video. 
        video: assets/videos/CIS581.mov

    Multi-Robot Sorting System:
        name: Multi-Robot Parcel Sorting System
        description: Designed simulation for multi-robot parcel sorting systems on ROS. The simulation worked for 120 robots that independently planned their paths and avoided collisions. Created software to evaluate the efficiency of the simulation. Additionally worked on the control software for onboard micro-controllers to build a complete proof of concept.  
        video: assets/videos/addverb.mp4
    

    Unmanned Ground Vehicles Team:
        name: Unmanned Ground Vehicle, DTU 2017-2018
        description: Founded and led a team of 6 students in building a automated ground vehicle under the Robot Operating System to participate in the IGVC competition held in Oakland, U.S.A. Responsible for team operations, raising funds and embedded systems development. My work involved interfacing the IMU and motor drivers through the microcontroller to communicate with the main system as a ROS node.
        video: assets/videos/ugv.webm	      

#    Tangible User Interface for Smart Mirror:
#        name: Tangible User Interface for Smart Mirror
#        description: This project under Prof.Aman Parnami at IIITD, Weave Lab, explored the application of a tangible user interface for mirrors of the future. Various interaction use cases were ideated that explored areas such as sharing stories, post-surgery rehabilitation and construction toolkits. My work involved writing the image processing, UI and embedded systems code under open-frameworks. It also involved writing use-cases and ideating with the team.
#	 video: abc.mp4  
     

    
    Ecofrost Technologies Pvt. Ltd.:
        name: Ecofrost Technologies, Internship, Pune 2017-2018
        description: During my internship, I was tasked with the conception of a charge measurement device for thermal storage batteries which cannot be measured using conventional methods. After researching different methods, I choose capacitive sensing because it did not involve moving parts and provided high resolution sensing. I used TI's capacitive to digital converters and Atmels mirocontrollers to develop a prototype system. My work involved designing the PCBs which required careful deliberation because we were dealing primarily with capacitance. It also involved developing firmware, design of experiments for testing, debugging, collection, visualisation and analysis of data from the sensor. At the end of the internship, I presented my results and offered a new approach to attain the objective of energy management for the system using the same sensor based on the learnings from the test experiments.
        video: assets/videos/eco.webm
      
 
    Smart Dustbin Project:
        name: Smart Dustbin Project, WeConvert, New Delhi 2017-2018
        description: The Smart dustbin was a Raspberry-Pi based system to classify waste objects and reward the user with credits based on what is dropped in the bin. It makes use of Image Processing alogorithms to classify objects and sort trash. My work involved developing the detection algorithms, human machine interface and firmware for the embedded systems.The system was tested at various colleges, malls, and public places. The initiative was covered by media agencies such as DuBeat, Your Story and ZeeTv.
        video: assets/videos/weconvert.webm 	
 
    Three Degree Of Freedom Robotic Arm:
        name: Three Degree of Freedom Robotic Arm
        description: This was built in a team of three for my minor project in university during my undergraduate career. My work involved making the robot description files(URDFs), setting up MoveIt and sending goal positions to the micro-controller using the ROS framework.
        video: assets/videos/arm.webm 

    Object Follower:
        name: Object Follower
        description: Raspberry Pi based system that tracks an object in the HSV color space using blob detection and controls the motors such that the object lies in the center of the camera frame. 
        video: assets/videos/Track.webm
      
    Beat Detection:
        name: Beat Detection
        description: This project involved performing FFT on audio signals for beat detection and controlling servo motors to react to the sensed beats.
        video: assets/videos/beat.mp4
       
    Line Follower Robot:
        name: Line Follower Robot
        description: This is a simple line follower built using light sensitive resistors and automatic calibration for different lighting scenarios.
        video: assets/videos/Line_Follower.webm
        
    Artist:
        name: Artist
        description: This is a simple project made using junk material to draw simple shapes using the motor assembly controlled by an 8 bit atmel micro-controller through L293D motor driver.
        video: assets/videos/Artist.mp4

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
